services:
  - type: web
    name: krishikaya-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && gunicorn backend.wsgi:application --config gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: ALLOWED_HOSTS
        value: ".onrender.com" 